name:                dnamotifs
version:             0.1.0.0
license:             BSD3
author:              "Sébastian Méric de Bellefon"
maintainer:          "arnaudpourseb@gmail.com"
copyright:           "Sébastian Méric de Bellefon"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Find motifs in DNA sequences using the Jaccard distance
description:         Find motifs in DNA sequences using the Jaccard distance

dependencies:
- base >= 4.7 && < 5
- vector
- time
- raw-strings-qq
- inline-c
- attoparsec
- text
- bytestring
- zlib
- either
- dlist
- containers
- derive-storable
- derive-storable-plugin
- text-show
- vector-algorithms
- deepseq
- pipes
- pipes-zlib
- pipes-bytestring
- split
- transformers
- mtl
- filepath
- QuickCheck
- rio

default-extensions: NoImplicitPrelude

ghc-options:
  - -Wall
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wcompat
  - -Widentities
  - -Wpartial-fields
  - -Wredundant-constraints
  - -fwarn-unused-imports
 # - -fplugin Foreign.Storable.Generic.Plugin   # Is supposed to make Storable instances faster. Doesn't seem to make a difference

_exe-ghc-options: &exe-ghc-options
  - -rtsopts
  #- -with-rtsopts=-N
  - -O2
  - -Wall
 # - -Werror

library:
    source-dirs:
      - app
      - src
    ghc-options:
      - -Wall
  
executables:
  dnamotifs:
    main:        Main.hs
    source-dirs:
      - app
    ghc-options: *exe-ghc-options
    dependencies:
      - dnamotifs

tests:
  cmodule-test:
    main: Main.hs
    source-dirs:
      - test
    dependencies:
      - QuickCheck
      - HTF
      - dnamotifs
