name:                dnamotifs
version:             0.1.0.0
license:             BSD3
author:              "Sébastian Méric de Bellefon"
maintainer:          "arnaudpourseb@gmail.com"
copyright:           "Sébastian Méric de Bellefon"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Find motifs in DNA sequences using the Jaccard distance
description:         Find motifs in DNA sequences using the Jaccard distance

dependencies:
- base >= 4.7 && < 5
- language-c-quote
- mainland-pretty
- vector
- time
- raw-strings-qq
- inline-c

ghc-options:
  - -Wall
  - -Werror
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates

_exe-ghc-options: &exe-ghc-options
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

executables:
  01-hello-world:
    main:        Main.hs
    source-dirs:
      - app
      - src
    ghc-options: *exe-ghc-options

tests:
  cmodule-test:
    main: Main.hs
    source-dirs:
      - test
      - src
    dependencies:
      - QuickCheck
      - HTF